inrooms_trade_offers/cart/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^cart/(?P<object_id>\d+)/export/$', views.CartExport.as_view(), name='cart-export'),
]

inrooms_trade_offers/invoices/api/urls.py
from django.conf import urls
from rest_framework.routers import DefaultRouter

from .views import (
    InvoiceItemViewSet,
    InvoiceViewSet,
    PayingViewSet,
    ReportMutualPaymentsView,
    ReportOfficePlanView,
    ReportMutualPaymentsExport,
)

router = DefaultRouter()
router.register(r'invoice', InvoiceViewSet, base_name='invoice')
router.register(r'invoice/(?P<invoice_pk>\d+)/items', InvoiceItemViewSet, base_name='invoice_item'),
router.register(r'paying', PayingViewSet, base_name='paying')


urlpatterns = [
    urls.url(r'^', urls.include(router.urls)),
    urls.url(r'^reports/mutual_payments/export/$', ReportMutualPaymentsExport.as_view(), name='report_mutual_payments_export'),
    urls.url(r'^reports/mutual_payments/$', ReportMutualPaymentsView.as_view(), name='report_mutual_payments'),
    urls.url(r'^reports/office_plan/$', ReportOfficePlanView.as_view(), name='report_office_plan'),
]

inrooms_trade_offers/invoices/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^invoice/(?P<object_id>\d+)/export/$', views.InvoiceExport.as_view(), name='invoice-export'),
]

inrooms_trade_offers/invoices/models.py
from decimal import Decimal

from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models.signals import post_save
from django.dispatch.dispatcher import receiver
from django.utils import timezone
from model_utils.choices import Choices
from model_utils.models import TimeStampedModel

from core.utils.constants import ORDER_CATEGORY_CHOICE, DEPARTMENT_CHOICE, INVOICE_KIND_CHOICES

VAT_RATE_CHOICES = Choices(
    (0, '_0', 'Без НДС'),
    (18, '_18', '18%'),
)


INVOICE_STATUS = Choices(
    (0, 'not_paid', 'Не оплачен'),
    (10, 'partially_paid', 'Частично оплачен'),
    (100, 'paid', 'Оплачен'),
)


def default_invoice_month():
    return timezone.now().month


def default_invoice_year():
    return timezone.now().year


class Invoice(TimeStampedModel):
    STATUS = INVOICE_STATUS
    VAT_RATE = VAT_RATE_CHOICES
    ORDER_CATEGORY = ORDER_CATEGORY_CHOICE
    KIND = INVOICE_KIND_CHOICES

    kind = models.PositiveSmallIntegerField('Тип', choices=KIND, default=KIND.default)
    payment_perion_month = models.PositiveSmallIntegerField('Платежный период. Месяц',
                                                            default=default_invoice_month,
                                                            validators=[
                                                                MaxValueValidator(12),
                                                                MinValueValidator(1)
                                                            ])
    payment_perion_year = models.PositiveSmallIntegerField('Платежный период. Год',
                                                           default=default_invoice_year,
                                                           validators=[
                                                               MaxValueValidator(3000),
                                                               MinValueValidator(2000)
                                                           ])
    is_active = models.BooleanField('Активен?', default=True)
    status = models.PositiveSmallIntegerField('Статус', choices=STATUS, default=STATUS.not_paid)
    amount_paid = models.DecimalField('Сумма оплачено', max_digits=20, decimal_places=2, default=Decimal('0.00'))
    number = models.CharField('Номер', max_length=50, blank=True, default='')
    provider = models.ForeignKey('clients.Client', verbose_name='Поставщик',
                                   related_name='invoice_provider', on_delete=models.PROTECT)
    customer = models.ForeignKey('clients.Client', verbose_name='Получатель',
                                 related_name='invoice_customer', on_delete=models.PROTECT)
    vat_rate = models.PositiveSmallIntegerField('Ставка НДС', choices=VAT_RATE, default=VAT_RATE._0)
    category = models.PositiveSmallIntegerField('Категория', choices=ORDER_CATEGORY, default=ORDER_CATEGORY.white)

    total_price = models.DecimalField('Cумма', max_digits=20, decimal_places=10, default=0)

    comment = models.TextField('Комментарий', blank=True)

    class Meta:
        verbose_name = 'Счет'
        verbose_name_plural = 'Счета'
        ordering = ('-id', )

    def __str__(self):
        return 'Счет №:{}, id:{}'.format(self.number, self.id)

    def save(self, *args, **kwargs):
        self.set_number()
        self.total_price = self.get_total_price()
        super().save(*args, **kwargs)

    def set_number(self):
        if not self.number:
            if int(self.category) == self.ORDER_CATEGORY.white:
                numbers = [
                    int(n) for n in Invoice.objects.filter(
                        category=self.ORDER_CATEGORY.white).values_list('number', flat=True) if n.isdigit()
                ]
                if numbers:
                    self.number = str(sorted(numbers)[-1] + 1)
                else:
                    self.number = '1'
            else:
                numbers = [
                    int(n[1:]) for n in Invoice.objects.filter(
                        category=self.ORDER_CATEGORY.black).values_list('number', flat=True).exclude(number='') if n[0] == 'R' and n[1:].isdigit()
                ]
                if numbers:
                    self.number = 'R{}'.format(str(sorted(numbers)[-1] + 1))
                else:
                    self.number = 'R1'

    def get_price(self):
        price = Decimal('0.00')
        for i in self.items.all():
            price += i.get_full_price()
        return price

    def get_vat_price(self):
        price = self.get_price()
        return (price * self.vat_rate) / 100

    def get_total_price(self):
        return self.get_price() + self.get_vat_price()


UNIT_CHOICE = Choices(
    ('1', 'units', '1'),
    ('pieces', 'pieces', 'шт'),
    ('packings', 'packings', 'уп'),
)


class InvoiceItem(models.Model):
    UNIT = UNIT_CHOICE
    invoice = models.ForeignKey(Invoice, verbose_name='Счет', related_name='items', on_delete=models.CASCADE)
    product_name = models.CharField('Название товара', max_length=500)
    count = models.PositiveIntegerField('Количество')
    price = models.DecimalField('Цена (шт)', max_digits=20, decimal_places=10)
    unit = models.CharField('Единица измерения', max_length=50, choices=UNIT, default=UNIT.units)

    class Meta:
        verbose_name = 'Товар в счете'
        verbose_name_plural = 'Товары в счете'
        ordering = ('-id', )

    def __str__(self):
        return 'Товар в счете {}, id:{}'.format(self.invoice_id, self.id, )

    def get_full_price(self):
        return self.count * self.price


class Paying(TimeStampedModel):
    invoice = models.ForeignKey(Invoice, verbose_name='Счёт (Основание)')
    department = models.PositiveSmallIntegerField('Отдел', choices=DEPARTMENT_CHOICE, default=DEPARTMENT_CHOICE.development)

    number = models.CharField('Номер платежа', max_length=100)
    date = models.DateField('Дата платежа')

    include_to_office_plan = models.BooleanField('Добавлять в офис план?', default=True)
    include_to_dashboard = models.BooleanField('Включать в дашборд', default=True)

    amount = models.DecimalField('Сумма', max_digits=12, decimal_places=2)

    comment = models.TextField('Комментарий', blank=True)

    class Meta:
        verbose_name = 'Платеж'
        verbose_name_plural = 'Платежи'
        ordering = ('id', )

    def __str__(self):
        return '{}'.format(self.id)


class OfficePlan(models.Model):
    year = models.PositiveSmallIntegerField('Год')
    department = models.PositiveSmallIntegerField('Отдел', choices=DEPARTMENT_CHOICE)
    month_1 = models.DecimalField('Январь', max_digits=10, decimal_places=2, default=Decimal('0.00'))
    month_2 = models.DecimalField('Февраль', max_digits=10, decimal_places=2, default=Decimal('0.00'))
    month_3 = models.DecimalField('Март', max_digits=10, decimal_places=2, default=Decimal('0.00'))
    month_4 = models.DecimalField('Апрель', max_digits=10, decimal_places=2, default=Decimal('0.00'))
    month_5 = models.DecimalField('Май', max_digits=10, decimal_places=2, default=Decimal('0.00'))
    month_6 = models.DecimalField('Июнь', max_digits=10, decimal_places=2, default=Decimal('0.00'))
    month_7 = models.DecimalField('Июль', max_digits=10, decimal_places=2, default=Decimal('0.00'))
    month_8 = models.DecimalField('Август', max_digits=10, decimal_places=2, default=Decimal('0.00'))
    month_9 = models.DecimalField('Сентябрь', max_digits=10, decimal_places=2, default=Decimal('0.00'))
    month_10 = models.DecimalField('Октябрь', max_digits=10, decimal_places=2, default=Decimal('0.00'))
    month_11 = models.DecimalField('Ноябрь', max_digits=10, decimal_places=2, default=Decimal('0.00'))
    month_12 = models.DecimalField('Декабрь', max_digits=10, decimal_places=2, default=Decimal('0.00'))

    class Meta:
        verbose_name = 'Офис-план'
        verbose_name_plural = 'Офис-планы'
        ordering = ('-year', )

    def __str__(self):
        return '{}, {}'.format(self.year, self.get_department_display())

inrooms_trade_offers/invoices/forms.py
from autocomplete_light import shortcuts as autocomplete_light
from django import forms


class InvoiceAdminForm(forms.ModelForm):

    class Meta:
        widgets = {
            'provider': autocomplete_light.ChoiceWidget('ClientAutocomplete'),
            'customer': autocomplete_light.ChoiceWidget('ClientAutocomplete'),
        }


class PayingAdminForm(forms.ModelForm):

    class Meta:
        widgets = {
            'invoice':  autocomplete_light.ChoiceWidget('InvoiceAutocomplete')
        }

inrooms_trade_offers/invoices/api/views/invoice.py
import django_filters
from django.db.models.aggregates import Sum
from django.utils import timezone
from rest_framework import filters
from rest_framework.viewsets import ModelViewSet

from core.utils.views.additional_data_pagination import AdditionalDataPaginatedViewMixin
from history.models import HistoryItem
from ..serializers import InvoiceSerializer
from ...models import Invoice


def filter_to_create_paying(queryset, value):
    if value:
        queryset = queryset.filter(status__in=[Invoice.STATUS.not_paid, Invoice.STATUS.partially_paid])
    else:
        queryset = queryset.exclude(status__in=[Invoice.STATUS.not_paid, Invoice.STATUS.partially_paid])
    return queryset


class InvoiceFilterSet(django_filters.FilterSet):
    to_create_paying = django_filters.BooleanFilter(action=filter_to_create_paying)

    class Meta:
        model = Invoice
        fields = [
            'to_create_paying',
            'provider',
            'customer',
            'status',
            'kind',
        ]


class InvoiceViewSet(AdditionalDataPaginatedViewMixin, ModelViewSet):
    serializer_class = InvoiceSerializer
    filter_class = InvoiceFilterSet
    filter_backends = (filters.SearchFilter, filters.DjangoFilterBackend, filters.OrderingFilter)
    search_fields = ('=id', 'number', 'customer__name')
    ordering_fields = (
        'id',
        'number',
        'created',
        'modified',
        'provider__name',
        'customer__name',
    )

    def get_queryset(self):
        qs = Invoice.objects.filter(is_active=True)
        qs = qs.select_related('customer', 'provider')
        return qs

    def perform_create(self, serializer):
        serializer.save()
        history_item = HistoryItem.objects.create(
            kind=HistoryItem.KIND.invoice_create,
            content_object=serializer.instance,
            body='Пользователь {} {} создал счет №{}'.format(
                self.request.user.name,
                timezone.now().strftime('%d.%m.%Y %H:%M'),
                serializer.instance.id,
            ),
        )

    def get_additional_data(self, queryset):
        data = queryset.aggregate(Sum('total_price'))
        return {
            'total_price_sum': data['total_price__sum'],
        }

inrooms_trade_offers/invoices/api/views/invoice_item.py
from rest_framework import filters
from rest_framework.generics import get_object_or_404
from rest_framework.viewsets import ModelViewSet

from ..serializers import InvoiceItemSerializer
from ...models import Invoice, InvoiceItem


class InvoiceItemViewSet(ModelViewSet):
    serializer_class = InvoiceItemSerializer
    filter_backends = (filters.SearchFilter, )
    search_fields = ('product_name', )
    queryset = InvoiceItem.objects.all()
    ordering_fields = (
        'id',
        'product_name',
        'quantity',
        'price'
    )

    def dispatch(self, request, invoice_pk: int, *args, **kwargs):
        self.invoice = get_object_or_404(Invoice, pk=invoice_pk)
        return super(InvoiceItemViewSet, self).dispatch(request, *args, **kwargs)

    def perform_create(self, serializer):
        instance = serializer.save(invoice=self.invoice)
        self.invoice.save()
        return instance

    def perform_update(self, serializer):
        super().perform_update(serializer)
        self.invoice.save()

    def perform_destroy(self, instance):
        super().perform_destroy()
        self.invoice.save()

    def get_queryset(self):
        qs = super(InvoiceItemViewSet, self).get_queryset()
        qs = qs.filter(invoice=self.invoice)
        return qs

inrooms_trade_offers/invoices/api/views/paying.py
import django_filters
from django.db.models.aggregates import Sum
from rest_framework import filters
from rest_framework.viewsets import ModelViewSet

from core.utils.views.additional_data_pagination import AdditionalDataPaginatedViewMixin
from ..serializers import PayingSerializer
from ...models import Paying


def filter_date_year(queryset, value):
    if value:
        queryset = queryset.filter(date__year=value)
    return queryset


def filter_date_month(queryset, value):
    if value:
        queryset = queryset.filter(date__month=value)
    return queryset


class PayingFilterSet(django_filters.FilterSet):
    date_year = django_filters.NumberFilter(action=filter_date_year)
    date_month = django_filters.NumberFilter(action=filter_date_month)

    class Meta:
        model = Paying
        fields = (
            'invoice',
            'invoice__customer',
            'department',
            'date_year',
            'date_month',
            'include_to_office_plan',
            'invoice__kind'
        )


class PayingViewSet(AdditionalDataPaginatedViewMixin, ModelViewSet):
    serializer_class = PayingSerializer
    filter_class = PayingFilterSet
    filter_backends = (filters.SearchFilter, filters.DjangoFilterBackend, filters.OrderingFilter)
    search_fields = ('=id', 'number')
    queryset = Paying.objects.all().order_by('-date')
    ordering_fields = (
        'id',
        'number',
        'created',
        'modified',
        'date',
    )

    def get_additional_data(self, queryset):
        data = queryset.aggregate(Sum('amount'))
        return {
            'amount_sum': data['amount__sum'],
        }

inrooms_trade_offers/invoices/views.py
import datetime

from django.shortcuts import get_object_or_404
from pytils import numeral
from wkhtmltopdf.views import PDFTemplateView

from .models import Invoice


class InvoiceExport(PDFTemplateView,):
    template_name = 'invoices/invoice_pdf.html'
    filename = 'invoice.pdf'
    filename_docx = 'invoice.docx'

    def dispatch(self, request, object_id, *args, **kwargs):
        self.object = get_object_or_404(Invoice, id=object_id)
        self.print_pechat = True if request.GET.get('print_pechat', None) else False
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        items = []
        items_part = []
        qs = self.object.items.all()
        for item in qs:
            items_part.append(item)
            if (not items and len(items_part) >= 5) or (item and len(items_part) >= 6):
                items.append(items_part)
                items_part = []
        if items_part:
            items.append(items_part)
        context['print_pechat'] = self.print_pechat
        context['invoice'] = self.object
        context['items'] = items
        context['vat_price'] = self.object.get_vat_price()
        context['total_price'] = self.object.get_price() + context['vat_price']
        context['total_price_left'] = int(context['total_price'])
        context['total_price_right'] = int((context['total_price'] - int(context['total_price'])) * 100)
        context['total_price_string'] = numeral.rubles(context['total_price'], zero_for_kopeck=True)
        context['footer_on_new_page'] = False
        if len(items) > 1:
            if len(items[-1]) >= 6:
                context['footer_on_new_page'] = True
        elif len(items):
            if len(items[-1]) >= 5:
                context['footer_on_new_page'] = True
        context['pages_count'] = len(items) + (1 if context['footer_on_new_page'] else 0)
        return context

    def get_filename(self):
        today = datetime.date.today()
        return "Счет {}, {}.pdf".format(self.object.number, today.strftime("%d.%m.%Y"))

inrooms_trade_offers/invoices/templates/invoices/invoice_pdf.html
{% extends 'blank_page.html' %}

{% load thumbnail %}
{% load humanize %}

{% block style %}
  <style>
    table {
      width: 964px;
      margin: 0 auto;
      border-bottom: 1px solid gray;
      border-spacing: 0;
      border-collapse: collapse;
      margin-top: 40px;
    }
    td, th {
      padding: 0 1px;
      border: 2px solid black;
    }
    th {
      text-align: left;
    }
    .row {
      position: relative;
      overflow: hidden;
    }
    .clear {
        clear: both;
    }
    body {
      width: 1024px;
      background: white;
      font-family: Arial, Helvetica, sans-serif;
      font-size: 18px;
    }
    img {
      height: 200px;
    }

  </style>
  <script>
    window.print()
  </script>
{% endblock %}

{% block content %}
  <div style="text-align: center;margin: 40px 0 10px 0;font-size: 16px;">
    Внимание! Оплата данного счета означает согласие с условиями поставки товара. Уведомление об оплате<br>
    обязательно, в противном случае не гарантируется наличие товара на складе. Товар отпускается по факту<br>
    прихода денег на р/с Поставщика, самовывозом, при наличии доверенности и паспорта.
  </div>
  <table style="margin-top: 22px;">
    <tr>
      <td colspan="2" rowspan="2" style="width: 55%;">
        <div style="min-height: 50px;">
          {{ invoice.provider.bank_name }}
        </div>
        <div style="font-size: 16px;">
          Банк получателя
        </div>
      </td>
      <td style="width: 10%;">
        БИК
      </td>
      <td style="width: 30%;border-bottom: 0px;">
        {{ invoice.provider.bik }}
      </td>
    </tr>
    <tr>
      <td>Сч. №</td>
      <td style="border-top: 0px;">{{ invoice.provider.account_current }}</td>
    </tr>
    <tr>
      <td style="width: 30%;height: 26px;">ИНН&nbsp;&nbsp;&nbsp;&nbsp;{{ invoice.provider.inn }}</td>
      <td>КПП&nbsp;&nbsp;&nbsp;&nbsp;{{ invoice.provider.kpp }}</td>
      <td style="border-bottom: 0px;">Сч. №</td>
      <td style="border-bottom: 0px;">{{ invoice.provider.account_correspondent }}</td>
    </tr>
    <tr>
      <td colspan="2">
        <div style="min-height: 32px;">
          {{ invoice.provider.name }}
        </div>
        <div style="font-size: 16px;">
          Получатель
        </div>
      </td>
      <td style="border-top: 0px;"></td>
      <td style="border-top: 0px;"></td>
    </tr>
  </table>
  <div style="text-align: left;margin: 20px auto 10px auto;font-size: 28px;width: 964px;">
    <strong>Счет на оплату № {{ invoice.number }} от {{ invoice.created|date:"d.m.Y" }}.</strong>
    <hr style="border-top: 3px solid black;">
  </div>
  <div style="text-align: left;margin: 10px auto;width: 964px;">
   <table style="border: 0;margin-top: 0px;">
     <tr style="border: 0;width: 1%;">
       <td style="border: 0;font-size: 16px;vertical-align: top;">Поставщик:</td>
       <td style="border: 0;vertical-align: top;">
         <div style="padding-bottom: 30px;">
         <b>
           {{ invoice.provider.name }}{% if invoice.provider.inn %},
              ИНН {{ invoice.provider.inn }}{% endif %}{% if invoice.provider.kpp %},
              КПП {{ invoice.provider.kpp }}{% endif %}{% if invoice.provider.get_full_legal_address %},
              {{ invoice.provider.get_full_legal_address }}{% endif %}{% if invoice.provider.phone %},
              тел.: {{ invoice.provider.phone }}{% endif %}
         </b>
         </div>
       </td>
     </tr>
     <tr style="border: 0;">
       <td style="border: 0;font-size: 16px;vertical-align: top;">Покупатель:</td>
       <td style="border: 0;vertical-align: top;">
         <b>
           {{ invoice.customer.name }}{% if invoice.customer.inn %},
              ИНН {{ invoice.customer.inn }}{% endif %}{% if invoice.customer.kpp %},
              КПП {{ invoice.customer.kpp }}{% endif %}{% if invoice.customer.get_full_legal_address %},
              {{ invoice.customer.get_full_legal_address }}{% endif %}{% if invoice.customer.phone %},
              тел.: {{ invoice.customer.phone }}{% endif %}
         </b>
       </td>
     </tr>
   </table>
  </div>

  <table style="border: 0px;margin-top: 20px;border-top: 4px solid black;">
    <tr style="border-left: 4px solid black;border-right: 4px solid black;">
      <td style="width: 4.5%; height: 50px; text-align: center; font-weight: bold;">№</td>
      <td style="text-align: center; font-weight: bold;">Товары (работы, услуги)</td>
      <td style="width: 8.5%; text-align: center; font-weight: bold;">Кол-во</td>
      <td style="width: 6.7%; text-align: center; font-weight: bold;">Ед.</td>
      <td style="width: 13.4%; text-align: center; font-weight: bold;">Цена</td>
      <td style="width: 14.6%; text-align: center; font-weight: bold;">Сумма</td>
    </tr>
    {% for item in invoice.items.all %}
      <tr style="border-left: 4px solid black;border-right: 4px solid black;{% if forloop.last %}border-bottom: 4px solid black;{% endif %}">
        <td style="text-align: center;font-size: 16px;vertical-align: top;">{{ forloop.counter }}</td>
        <td style="vertical-align: top;"><div style="min-height: 60px;">{{ item.product_name }}</div></td>
        <td style="text-align: center;vertical-align: top;">{{ item.count }}</td>
        <td style="text-align: center;vertical-align: top;">{{ item.get_unit_display }}</td>
        <td style="text-align: center;vertical-align: top;">{{ item.price|floatformat:2|intcomma }}</td>
        <td style="text-align: center;vertical-align: top;">{{ item.get_full_price|floatformat:2|intcomma }}</td>
      </tr>
    {% endfor %}
    <tr style="vertical-align: bottom;font-size: 17px;">
      <td colspan="5" style="text-align: right; font-weight: bold; border: 0px;height: 30px;">Итого:</td>
      <td style="border: none;font-weight: bold;text-align: right;">{{ invoice.get_price|floatformat:2|intcomma }}</td>
    </tr>
    <tr style="vertical-align: bottom;font-size: 17px;">
      <td colspan="5" style="text-align: right; font-weight: bold; border: 0px;height: 30px;">НДС:</td>
      <td style="border: none;font-weight: bold;text-align: right;">{{ vat_price|floatformat:2|intcomma }}</td>
    </tr>
    <tr style="vertical-align: bottom;font-size: 17px;">
      <td colspan="5" style="text-align: right; font-weight: bold; border: 0px;height: 30px;">Всего к оплате:</td>
      <td style="border: none;font-weight: bold;text-align: right;">{{ total_price|floatformat:2|intcomma }}</td>
    </tr>
  </table>
  <div class="pechat" style="width: 964px;margin: 0 auto;position:relative;">
    {% if print_pechat %}
      {% if invoice.provider.code == 'ooo-bass-invest' %}
        <div style="position: absolute;z-index: -1;top: -17px;left: 50px;">
          <img src="/static/img/pechat.png" alt="" style="-webkit-print-color-adjust: exact;width: 500px;height: 500px;">
        </div>
      {% endif %}
    {% endif %}
    <div style="text-align: left;margin: 10px 0;">
      Всего наименований {{ invoice.items.count }}, на сумму {{ total_price|floatformat:2|intcomma }} руб.
    </div>
    <div style="text-align: left;margin: 10px 0;">
      <strong>{{ total_price_string|capfirst }}</strong>
    </div>
    <hr style="border-top: 3px solid black;margin-top: 30px;">
    <table style="border: none;">
      <tr>
        <td style="width: 1%;border: none;padding-right: 15px;font-weight: bold;">
          Руководитель
        </td>
        <td style="width: 50%;font-size: 16px;text-align: right;border-left: none;border-right: none; border-top: none;">
          {{ invoice.provider.head }}
        </td>
        <td style="width: 1%;border: none;padding-right: 15px;padding-left: 15px;font-weight: bold;">
          Бухгалтер
        </td>
        <td style="width: 50%;font-size: 16px;text-align: right;border-left: none;border-right: none; border-top: none;">
          {{ invoice.provider.accountant_general }}
        </td>
      </tr>
    </table>
  </div>


{% endblock %}